services:
  postgres:
<<<<<<< HEAD
    container_name: postgreSQL
=======
>>>>>>> origin/frontend_yesi
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=sharefly
  adminer:
<<<<<<< HEAD
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=dracula
=======
    image: adminer
    restart: always
    ports:
      - 8080:8080
>>>>>>> origin/frontend_yesi
