services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=sharefly
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080